plugins:
  - rubocop-performance
  - rubocop-rspec

require:
  - ./lib/rubocop/cop/smolagents

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'examples/**/*'

# =============================================================================
# Layout
# =============================================================================

Layout/LineLength:
  Max: 180

# =============================================================================
# Style
# =============================================================================

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

# YARD provides comprehensive documentation - class-level comments are redundant
# when YARD tags describe purpose, params, returns, examples, etc.
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# =============================================================================
# Ruby 4.0 Idiom Enforcement
# =============================================================================

# def name = @name.to_s
Style/EndlessMethod:
  EnforcedStyle: allow_single_line

# {name:, age:} instead of {name: name, age: age}
Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: always

# users.map { _1.name }
Style/NumberedParameters:
  EnforcedStyle: allow_single_line

# Person = Data.define(:name) { def greet = "Hi" }
Style/DataInheritance:
  Enabled: true

# Forbid OpenStruct - use Data.define or Hash
Style/OpenStructUse:
  Enabled: true

# =============================================================================
# Metrics
# =============================================================================

Metrics/BlockLength:
  Exclude:
    - 'smolagents.gemspec'

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 200

Metrics/AbcSize:
  Max: 55

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/PerceivedComplexity:
  Max: 16

Metrics/ParameterLists:
  Max: 13

# =============================================================================
# Naming
# =============================================================================

Naming/MethodName:
  AllowedPatterns:
    - '\ABuilder\z'

# =============================================================================
# Lint
# =============================================================================

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/SuppressedException:
  Exclude:
    - 'lib/smolagents/executors/docker.rb'

# =============================================================================
# Gemspec
# =============================================================================

Gemspec/DevelopmentDependencies:
  Enabled: false

# =============================================================================
# Smolagents Custom Cops
# =============================================================================

Smolagents/NoSleep:
  Enabled: true
  Exclude:
    - 'lib/smolagents/executors/docker.rb'

Smolagents/NoTimingAssertion:
  Enabled: true

Smolagents/NoTimeoutBlock:
  Enabled: true
  Exclude:
    - 'lib/smolagents/executors/docker.rb'

Smolagents/PreferDataDefine:
  Enabled: true
