plugins:
  - rubocop-performance
  - rubocop-rspec

require:
  - ./lib/rubocop/cop/smolagents

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'examples/**/*'
    - 'exploration/**/*'

# =============================================================================
# Layout
# =============================================================================

Layout/LineLength:
  Max: 120

# =============================================================================
# Style
# =============================================================================

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

# YARD provides comprehensive documentation - class-level comments are redundant
# when YARD tags describe purpose, params, returns, examples, etc.
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# =============================================================================
# Ruby 4.0 Idiom Enforcement
# =============================================================================

# def name = @name.to_s
Style/EndlessMethod:
  EnforcedStyle: allow_single_line

# {name:, age:} instead of {name: name, age: age}
Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: always

# users.map { _1.name }
Style/NumberedParameters:
  EnforcedStyle: allow_single_line

# Person = Data.define(:name) { def greet = "Hi" }
Style/DataInheritance:
  Enabled: true

# Forbid OpenStruct - use Data.define or Hash
Style/OpenStructUse:
  Enabled: true

# =============================================================================
# Metrics
# =============================================================================

Metrics/BlockLength:
  Exclude:
    - 'smolagents.gemspec'

# RuboCop defaults - inventory mode
# CountComments: false excludes YARD documentation from line counts
Metrics/MethodLength:
  Max: 10
  CountComments: false
  Exclude:
    - 'lib/smolagents/http/*.rb'              # Response handling has inherent branching
    - 'lib/smolagents/tools/*_search.rb'      # Search formatters are verbose
    - 'lib/smolagents/concerns/resilience/*.rb' # Retry patterns need flow control
    - 'lib/smolagents/concerns/agents/*.rb'   # Agent concerns have complex coordination
    - 'lib/smolagents/concerns/formatting/*.rb' # Formatting methods are verbose
    - 'lib/smolagents/concerns/execution/*.rb' # Execution has error handling

Metrics/ClassLength:
  Max: 100
  CountComments: false
  Exclude:
    - 'lib/smolagents/tools/search_tool.rb'   # Search tool has extensive config
    - 'lib/smolagents/runtime/agent_memory.rb' # Memory management adds necessary complexity

Metrics/ModuleLength:
  Max: 100
  CountComments: false
  Exclude:
    - 'lib/smolagents/builders/*.rb'          # Builder DSLs are intentionally comprehensive
    - 'lib/smolagents/concerns/execution/*.rb' # Execution modules have many helpers

Metrics/AbcSize:
  Max: 17
  Exclude:
    - 'lib/smolagents/http/*.rb'              # Response handling has many branches
    - 'lib/smolagents/tools/*_search.rb'      # Search tools parse complex responses
    - 'lib/smolagents/concerns/agents/*.rb'   # Agent concerns coordinate fibers

# WIP: Target is default (7). Progress: 16→0 at 10→8, next target: 7
Metrics/CyclomaticComplexity:
  Max: 7
  Exclude:
    - 'lib/smolagents/http/*.rb'              # Response handling branches on status

# At RuboCop default
Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - 'lib/smolagents/http/*.rb'              # Response handling has inherent complexity

# Keyword args are Ruby's modern config pattern - don't count against limit
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

# =============================================================================
# Naming
# =============================================================================

Naming/MethodName:
  AllowedPatterns:
    - '\ABuilder\z'

# =============================================================================
# Lint
# =============================================================================

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/SuppressedException:
  Exclude:
    - 'lib/smolagents/executors/docker.rb'

# =============================================================================
# Smolagents Custom Cops
# =============================================================================

Smolagents/NoSleep:
  Enabled: true
  Exclude:
    - 'lib/smolagents/executors/docker.rb'

Smolagents/NoTimingAssertion:
  Enabled: true

Smolagents/NoTimeoutBlock:
  Enabled: true
  Exclude:
    - 'lib/smolagents/executors/docker.rb'

Smolagents/PreferDataDefine:
  Enabled: true
