plugins:
  - rubocop-performance
  - rubocop-rspec

require:
  - ./lib/rubocop/cop/smolagents

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'examples/**/*'
    - 'exploration/**/*'

# =============================================================================
# Layout
# =============================================================================

Layout/LineLength:
  Max: 120

# =============================================================================
# Style
# =============================================================================

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

# YARD provides comprehensive documentation
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# =============================================================================
# Ruby 4.0 Idiom Enforcement
# =============================================================================

# def name = @name.to_s
Style/EndlessMethod:
  EnforcedStyle: allow_single_line

# {name:, age:} instead of {name: name, age: age}
Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: always

# users.map { _1.name }
Style/NumberedParameters:
  EnforcedStyle: allow_single_line

# Person = Data.define(:name) { def greet = "Hi" }
Style/DataInheritance:
  Enabled: true

# Forbid OpenStruct - use Data.define or Hash
Style/OpenStructUse:
  Enabled: true

# =============================================================================
# Metrics - RuboCop Defaults
#
# Philosophy: If code is too complex, break it into smaller pieces.
# No file exclusions - every file should meet these standards.
# =============================================================================

Metrics/MethodLength:
  Max: 10
  CountComments: false

Metrics/ClassLength:
  Max: 100
  CountComments: false

Metrics/ModuleLength:
  Max: 100
  CountComments: false

Metrics/AbcSize:
  Max: 17

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 8

Metrics/BlockLength:
  Exclude:
    - 'smolagents.gemspec'

# Keyword args are Ruby's modern config pattern
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

# =============================================================================
# Naming
# =============================================================================

Naming/MethodName:
  AllowedPatterns:
    - '\ABuilder\z'

# =============================================================================
# Lint - Strict by Default
#
# Unused arguments are a code smell. If you declare it, use it.
# =============================================================================

# No blanket permission for unused keyword args - that led to defective tests
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: false

Lint/SuppressedException:
  Exclude:
    - 'lib/smolagents/executors/docker.rb'

# =============================================================================
# Smolagents Custom Cops
# =============================================================================

Smolagents/NoSleep:
  Enabled: true
  Exclude:
    - 'lib/smolagents/executors/docker.rb'
    - 'lib/smolagents/concerns/resilience/retry_execution.rb'
    - 'lib/smolagents/concerns/resilience/tool_retry.rb'

Smolagents/NoTimingAssertion:
  Enabled: true

Smolagents/NoTimeoutBlock:
  Enabled: true
  Exclude:
    - 'lib/smolagents/executors/docker.rb'

Smolagents/PreferDataDefine:
  Enabled: true
