AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'examples/**/*'

Layout/LineLength:
  Max: 180

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'smolagents.gemspec'

Metrics/MethodLength:
  Max: 70

Metrics/ClassLength:
  Max: 400

Metrics/AbcSize:
  Max: 65

Metrics/CyclomaticComplexity:
  Max: 17

Metrics/PerceivedComplexity:
  Max: 17

Metrics/ParameterLists:
  Max: 8

Lint/DuplicateBranch:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/MissingSuper:
  Enabled: false

Lint/UnreachableCode:
  Exclude:
    - 'spec/**/*'

Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MapIntoArray:
  Exclude:
    - 'spec/**/*'

Security/Eval:
  Exclude:
    - 'examples/**/*'
    - 'spec/**/*'

Gemspec/DevelopmentDependencies:
  Enabled: false
