plugins:
  - rubocop-performance
  - rubocop-rspec

require:
  - ./lib/rubocop/cop/smolagents

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'examples/**/*'

# Layout
Layout/LineLength:
  Max: 180

# Style
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/MultilineBlockChain:
  Enabled: false

Style/MapIntoArray:
  Exclude:
    - 'spec/**/*'

# Metrics - specs are excluded, lib has reasonable limits
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'smolagents.gemspec'

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 300
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 55
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/PerceivedComplexity:
  Max: 16

Metrics/ParameterLists:
  Max: 13

# Naming - allow flexibility
Naming/MethodParameterName:
  Enabled: false

Naming/BlockParameterName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/MethodName:
  AllowedPatterns:
    - '\ABuilder\z'

# Lint
Lint/DuplicateBranch:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/MissingSuper:
  Enabled: false

Lint/UnreachableCode:
  Exclude:
    - 'spec/**/*'

Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

Lint/SuppressedException:
  Exclude:
    - 'lib/smolagents/executors/docker.rb'
    - 'spec/**/*'

# Security
Security/Eval:
  Exclude:
    - 'examples/**/*'
    - 'spec/**/*'

# RSpec - reasonable limits
RSpec/ExampleLength:
  Max: 45
  Exclude:
    - 'spec/integration/**/*'

RSpec/MultipleExpectations:
  Max: 15

RSpec/NestedGroups:
  Max: 5

# RSpec - disabled for pragmatic testing
RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/Output:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/IteratedExpectation:
  Enabled: false

# Gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# =============================================================================
# Smolagents Custom Cops - Event-Driven Architecture Enforcement
# =============================================================================
# These cops enforce our event-driven design by preventing timing-dependent
# code from entering the codebase. Tests should be deterministic and fast.

# Forbid sleep() calls - use event-driven coordination instead
Smolagents/NoSleep:
  Enabled: true
  Description: "Use event-driven patterns (Queue, ConditionVariable) instead of sleep"
  # Docker executor tests use sleep in the code being executed, not test logic
  Exclude:
    - "lib/smolagents/executors/docker.rb"

# Forbid meaningless timing assertions like `be >= 0` on duration
Smolagents/NoTimingAssertion:
  Enabled: true
  Description: "Test timing with explicit values, not >= 0 assertions"

# Forbid Timeout.timeout - it corrupts state via Thread.raise
Smolagents/NoTimeoutBlock:
  Enabled: true
  Description: "Use circuit breakers or process-level timeouts instead"
  # Docker executor legitimately catches Timeout::Error from external processes
  Exclude:
    - "lib/smolagents/executors/docker.rb"
