plugins:
  - rubocop-performance
  - rubocop-rspec

require:
  - ./lib/rubocop/cop/smolagents

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'examples/**/*'
    - 'exploration/**/*'

# =============================================================================
# Layout
# =============================================================================

Layout/LineLength:
  Max: 120

# =============================================================================
# Style
# =============================================================================

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

# YARD provides comprehensive documentation
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# =============================================================================
# Ruby 4.0 Idiom Enforcement
# =============================================================================

# def name = @name.to_s
Style/EndlessMethod:
  EnforcedStyle: allow_single_line

# {name:, age:} instead of {name: name, age: age}
Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: always

# users.map { _1.name }
Style/NumberedParameters:
  EnforcedStyle: allow_single_line

# Person = Data.define(:name) { def greet = "Hi" }
Style/DataInheritance:
  Enabled: true

# Forbid OpenStruct - use Data.define or Hash
Style/OpenStructUse:
  Enabled: true

# =============================================================================
# Metrics - RuboCop Defaults
#
# Philosophy: If code is too complex, break it into smaller pieces.
# No file exclusions - every file should meet these standards.
# =============================================================================

Metrics/MethodLength:
  Max: 10
  CountComments: false

Metrics/ClassLength:
  Max: 100
  CountComments: false
  Exclude:
    - 'lib/smolagents/models/model.rb'
    - 'lib/smolagents/models/resilient_model.rb'
    - 'lib/smolagents/testing/mock_model.rb'
    - 'lib/smolagents/tools/search_tool/configuration.rb'
    - 'lib/smolagents/types/observability_context.rb'

Metrics/ModuleLength:
  Max: 100
  CountComments: false
  Exclude:
    - 'lib/smolagents/builders/agent_builder.rb'
    - 'lib/smolagents/concerns/agents/evaluation.rb'
    - 'lib/smolagents/persistence/agent_manifest.rb'
    - 'lib/smolagents/testing/requirement_builder.rb'
    - 'lib/smolagents/utilities/pattern_matching.rb'

Metrics/AbcSize:
  Max: 17
  Exclude:
    - 'lib/smolagents/concerns/agents/react_loop/repetition.rb'
    - 'lib/smolagents/concerns/validation/execution_oracle.rb'
    - 'lib/smolagents/concerns/validation/goal_drift/drift_analyzer.rb'
    - 'lib/smolagents/concerns/models/health/checks.rb'
    - 'lib/smolagents/testing/requirement_builder.rb'
    - 'lib/smolagents/tools/search_tool/configuration.rb'
    - 'lib/smolagents/types/model_config.rb'
    - 'script/*'

Metrics/CyclomaticComplexity:
  Max: 7
  Exclude:
    - 'lib/smolagents/builders/model_builder/build.rb'
    - 'lib/smolagents/concerns/agents/react_loop/repetition.rb'
    - 'lib/smolagents/concerns/models/reliability/configuration.rb'
    - 'lib/smolagents/concerns/resilience/retry_policy.rb'
    - 'lib/smolagents/concerns/validation/execution_oracle.rb'
    - 'lib/smolagents/concerns/validation/goal_drift/term_extractor.rb'
    - 'lib/smolagents/config/configuration.rb'
    - 'lib/smolagents/interactive/help.rb'
    - 'lib/smolagents/models/resilient_model.rb'
    - 'script/*'

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - 'lib/smolagents/concerns/agents/react_loop/repetition.rb'
    - 'lib/smolagents/concerns/resilience/retry_policy.rb'
    - 'lib/smolagents/concerns/validation/execution_oracle.rb'
    - 'script/*'

Metrics/BlockLength:
  Exclude:
    - 'smolagents.gemspec'

# Keyword args are Ruby's modern config pattern
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false
  Exclude:
    - 'lib/smolagents/models/model.rb'

# =============================================================================
# Naming
# =============================================================================

Naming/MethodName:
  AllowedPatterns:
    - '\ABuilder\z'

# =============================================================================
# Lint - Strict by Default
#
# Unused arguments are a code smell. If you declare it, use it.
# =============================================================================

# No blanket permission for unused keyword args - that led to defective tests
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: false

Lint/SuppressedException:
  Exclude:
    - 'lib/smolagents/executors/docker.rb'
    - 'spec/smolagents/logging_spec.rb'

Lint/UselessConstantScoping:
  Enabled: false

Lint/DuplicateBranch:
  Exclude:
    - 'lib/smolagents/config/configuration.rb'

# Constants in Data.define blocks are fine
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'lib/smolagents/types/*.rb'

Lint/MissingCopEnableDirective:
  Exclude:
    - 'script/*'

# =============================================================================
# Smolagents Custom Cops
# =============================================================================

Smolagents/NoSleep:
  Enabled: true
  Exclude:
    - 'lib/smolagents/executors/docker.rb'
    - 'lib/smolagents/concerns/resilience/retry_execution.rb'
    - 'lib/smolagents/concerns/resilience/tool_retry.rb'

Smolagents/NoTimingAssertion:
  Enabled: true

Smolagents/NoTimeoutBlock:
  Enabled: true
  Exclude:
    - 'lib/smolagents/executors/docker.rb'

Smolagents/PreferDataDefine:
  Enabled: true
