name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API (optional)
      description: If you have ideas for the API, show example code
      placeholder: |
        ```ruby
        # Example usage
        ```
      render: ruby

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other solutions or workarounds you've considered

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the library would this affect?
      options:
        - "Core Agent"
        - "Tools"
        - "Models"
        - "Builders/DSL"
        - "Events"
        - "Executors"
        - "New Module"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: Your estimate of implementation complexity
      options:
        - "Small - < 1 day"
        - "Medium - 1-3 days"
        - "Large - > 3 days"
        - "Unknown"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and this is not a duplicate
          required: true
        - label: This cannot be achieved with current abstractions
          required: true
        - label: I'm willing to submit a PR for this (optional)
