require_relative "smolagents/version"
require_relative "smolagents/errors"
require_relative "smolagents/data_types"
require_relative "smolagents/message_role"
require_relative "smolagents/chat_message"
require_relative "smolagents/memory"
require_relative "smolagents/tools/tool"
require_relative "smolagents/tools/tool_dsl"
require_relative "smolagents/tools/tool_collection"
require_relative "smolagents/tool_result"
require_relative "smolagents/lazy_tool_result"
require_relative "smolagents/tool_pipeline"
require_relative "smolagents/refinements"
require_relative "smolagents/instrumentation"

# Atomic concerns (ordered by dependencies)
require_relative "smolagents/concerns/http"
require_relative "smolagents/concerns/rate_limiter"
require_relative "smolagents/concerns/api_key"
require_relative "smolagents/concerns/json"
require_relative "smolagents/concerns/html"
require_relative "smolagents/concerns/xml"
require_relative "smolagents/concerns/results"
require_relative "smolagents/concerns/gem_loader"
require_relative "smolagents/concerns/tool_schema"
require_relative "smolagents/concerns/message_formatting"
require_relative "smolagents/concerns/monitorable"
require_relative "smolagents/concerns/streamable"
require_relative "smolagents/concerns/auditable"
require_relative "smolagents/concerns/circuit_breaker"
require_relative "smolagents/concerns/api"
require_relative "smolagents/concerns/step_execution"

require_relative "smolagents/default_tools"
require_relative "smolagents/pattern_matching"
require_relative "smolagents/template_renderer"
require_relative "smolagents/prompt_sanitizer"
require_relative "smolagents/configuration"
require_relative "smolagents/dsl"
require_relative "smolagents/executors"
require_relative "smolagents/monitoring"
require_relative "smolagents/models/model"
require_relative "smolagents/agents"
require_relative "smolagents/tools/managed_agent"

module Smolagents
  class Error < StandardError; end
end
