# RSpec-specific RuboCop configuration
inherit_from: ../.rubocop.yml

# =============================================================================
# Relaxed Rules for Test Code
# =============================================================================

# Tests often need long blocks for setup/assertions
Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# RSpec expect { }.to raise_error { } is idiomatic
Style/MultilineBlockChain:
  Enabled: false

Style/MapIntoArray:
  Enabled: false

# Short param names (n, x, e) are common in test code
Naming/MethodParameterName:
  Enabled: false

# Tests may have unreachable code for documentation
Lint/UnreachableCode:
  Enabled: false

# Empty blocks common in test setup
Lint/EmptyBlock:
  Enabled: false

# Constants in describe blocks are fine
Lint/ConstantDefinitionInBlock:
  Enabled: false

# Rescue nil patterns in test helpers
Lint/SuppressedException:
  Enabled: false

# Eval used in executor tests
Security/Eval:
  Enabled: false

# =============================================================================
# RSpec Cops - Limits
# =============================================================================

RSpec/ExampleLength:
  Max: 45
  Exclude:
    - 'spec/integration/**/*'

RSpec/MultipleExpectations:
  Max: 15

RSpec/NestedGroups:
  Max: 5

# =============================================================================
# RSpec Cops - Enabled
# =============================================================================
# ContextWording, MessageSpies, VerifiedDoubles, LetSetup,
# PendingWithoutReason, ExpectActual, Output, DescribedClass,
# IndexedLet, IteratedExpectation - all use defaults

# =============================================================================
# RSpec Cops - Disabled (Pragmatic)
# =============================================================================

# Complex specs legitimately need many helpers
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# File organization is pragmatic for integration tests
RSpec/SpecFilePathFormat:
  Enabled: false

# Related classes in one file is reasonable
RSpec/MultipleDescribes:
  Enabled: false

# Integration tests use string descriptions
RSpec/DescribeClass:
  Enabled: false

# Duplicate expectations are benign
RSpec/RepeatedExample:
  Enabled: false
