# RSpec-specific RuboCop configuration
inherit_from: ../.rubocop.yml

# =============================================================================
# Metrics - Reasonable Limits for Test Code
#
# Tests need some flexibility for setup, but should still be well-structured.
# Long tests should be broken into smaller, focused examples.
# =============================================================================

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/integration/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300

Metrics/AbcSize:
  Max: 30

# =============================================================================
# Style - Test-Specific Relaxations
# =============================================================================

# RSpec expect { }.to raise_error { } is idiomatic
Style/MultilineBlockChain:
  Enabled: false

# =============================================================================
# Lint - Test-Specific Relaxations
# =============================================================================

# Constants in describe blocks are fine for test fixtures
Lint/ConstantDefinitionInBlock:
  Enabled: false

# Security/Eval used in executor tests (testing code execution)
Security/Eval:
  Exclude:
    - 'spec/smolagents/executors/**/*'
    - 'spec/integration/readme_examples_spec.rb'

# =============================================================================
# RSpec Cops - Limits
# =============================================================================

RSpec/ExampleLength:
  Max: 30
  Exclude:
    - 'spec/integration/**/*'

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

# =============================================================================
# RSpec Cops - Pragmatic Disables
# =============================================================================

# Integration tests may need many helpers
RSpec/MultipleMemoizedHelpers:
  Max: 15

# File organization is pragmatic
RSpec/SpecFilePathFormat:
  Enabled: false

# Related classes in one file is reasonable for unit tests
RSpec/MultipleDescribes:
  Enabled: false

# Integration tests use string descriptions
RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
